# --- Spielerauswahl ---
SPIELER_AUSWAHL = [
    "Gaudi Sepp",
    "Brummbernd",
    "Schafkopf Schorsch",
    "Musi Mann",
    "Andrea",
    "Arne",
    "Basti",
    "Ben S.",
    "Bent",
    "Caro",
    "Charlotte",
    "Davina",
    "Daniel L.",
    "Eli",
    "Elias S.",
    "Elias Soltau",
    "Felix",
    "Ferdinand",
    "Franz",
    "Gerhard",
    "Hendrik",
    "Jakob",
    "Jonas H.",
    "Jonas L.",
    "Julik",
    "Kira",
    "Katharina",
    "Laura",
    "Leo",
    "Leif",
    "Liam",
    "Lukas F.",
    "Lukas H.",
    "Magnus",
    "Maja",
    "Marc",
    "Mattes",
    "Matze U.",
    "Maxl",
    "Monika",
    "Niclas N.",
    "Oli",
    "Reini",
    "Robin",
    "Roman",
    "Samuel",
    "Sophia",
    "Stefan K.",
    "Stephan M.",
    "Stephan S.",
    "Theo J.",
    "Tim Hasi",
    "Tim Plote",
    "Tim Pasta",
    "Thomas",
    "Thomas S.",
    "Vali",
    "Valentin W."
]

SPIELER_AUSWAHL_NEU = [
    "Gaudi Sepp",
    "Brummbernd",
    "Schafkopf Schorsch",
    "Musi Mann",
    "Arne Zander",
    "Basti Törner",
    "Ben S.",
    "Bent Nickl",
    "Caro",
    "Charlotte Heinemann",
    "Davina Döring",
    "Daniel Lender",
    "Eli",
    "Elias Schwarzkopf",
    "Elias Soltau",
    "Felix Roemer",
    "Ferdinand Unglert",
    "Franz",
    "Gerhard O.",
    "Hendrik Scharlau",
    "Jakob O.",
    "Jonas Hanke",
    "Jonas Lingener",
    "Julik",
    "Kira Frank",
    "Katharina",
    "Leo",
    "Leif Nickl",
    "Lukas Fuchs",
    "Lukas Hein",
    "Magnus",
    "Maja",
    "Marc",
    "Matze Unglert",
    "Maxl",
    "Monika",
    "Niclas Nickl",
    "Oli",
    "Reini",
    "Robin",
    "Roman",
    "Samuel",
    "Sophia Mayer",
    "Stefan Klaus",
    "Stephan Mayer",
    "Stephan Schaller",
    "Theo Jansen",
    "Tim Hasi",
    "Tim Plote",
    "Tim Pasta",
    "Thomas Karb",
    "Thomas Schaller",
    "Vali",
    "Valentin Wolff"
]


SPIELER_GRUPPEN = {
    "Alle": SPIELER_AUSWAHL,
    
    "Chaosclub": ["Ben S.", "Bent", "Julik", "Leif", "Magnus", "Marc", "Matze U.", "Robin", "Roman", "Vali", "Maja"],
    
    "Ak-Schafkopf Wü": ["Davina", "Daniel L.", "Elias S.", "Elias Soltau", "Hendrik", "Kira", "Maja", "Leo", "Lukas H.", "Samuel", "Stefan K.", "Tim Hasi", "Tim Plote", "Tim Pasta", "Theo J.", "Thomas", "Thomas S.", "Valentin W.", "Lukas F."],
    
    "Treuchtis": ["Arne", "Basti", "Eli", "Jonas L.", "Leo", "Maxl", "Oli", "Vali"],
}